### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by simon987** [C0nw0nk/Nginx-Lua-Anti-DDoS#21]
### Issue Description

Enabling the script makes nginx use 10Gb+ of RAM after a single HTTP request, making the whole system lock up.

### Versions:

- Browser(s): -
- Nginx version: `openresty/1.15.8.2`
- Operating system of web server running Nginx: `Debian 4.9.168-1+deb9u5`

### Nginx config:
```
server {
        listen 443 ssl;

       access_by_lua_file /etc/openresty/anti_ddos_challenge.lua;
       location ~ /(.*)$ {
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_pass http://127.0.0.1:4090/$1?$args;
        }
}
```

### Settings:

- I only changed the `local secret` line

**Comment by C0nw0nk** [comment]
I have been using it without being able to reproduce such memory leaks or issues it must be something else in your config or perhaps your installation of Lua.

Will see if more people can reproduce this.

**Comment by C0nw0nk** [comment]
@simon987 I had to disable Hex and my shuffler what are two encryption types due to firefox errors try the script with the update there and see if the memory leak continues perhaps it could be on of those methods that is the cause of your problem i stumbled across it when i checked firefox was seeing javascript errors.

**Comment by tamerciaga** [comment]
I am having the same issue here with the latest stable Openresty build (on CentOS 8), the error logs are showing this:
```
2020/03/01 19:09:52 [error] 9040#0: *446 lua entry thread aborted: memory allocation error: not enough memory
stack traceback:
coroutine 0:
        /usr/local/openresty/nginx/conf/anti_ddos_challenge.lua: in function 'stringrandom'
        /usr/local/openresty/nginx/conf/anti_ddos_challenge.lua:414: in function 'stringrandom'
        /usr/local/openresty/nginx/conf/anti_ddos_challenge.lua:414: in function 'stringrandom'
        /usr/local/openresty/nginx/conf/anti_ddos_challenge.lua:414: in function 'stringrandom'
        /usr/local/openresty/nginx/conf/anti_ddos_challenge.lua:414: in function 'stringrandom'
        /usr/local/openresty/nginx/conf/anti_ddos_challenge.lua:414: in function 'stringrandom'
        /usr/local/openresty/nginx/conf/anti_ddos_challenge.lua:414: in function 'stringrandom'
        /usr/local/openresty/nginx/conf/anti_ddos_challenge.lua:414: in function 'stringrandom'
        /usr/local/openresty/nginx/conf/anti_ddos_challenge.lua:414: in function 'stringrandom'
        /usr/local/openresty/nginx/conf/anti_ddos_challenge.lua:414: in function 'stringrandom'
        /usr/local/openresty/nginx/conf/anti_ddos_challenge.lua:578: in function 'encrypt_javascript'
        /usr/local/openresty/nginx/conf/anti_ddos_challenge.lua:946: in main chunk, client: IPHERE, server: XXX, request: "HEAD / HTTP/1.1", host: "XXX"
```

You can easily reproduce this using the following command several times (like 5x after each execution):
`curl -I hostnamehere`

It sends a HEAD request and causes nginx to use up all memory and crash. You can see it as a DoS-vulnerability. So it's not caused by Firefox. I will test your update later on.

@C0nw0nk I also sent you a message on Facebook regarding a project, please check it out :)

**Comment by tamerciaga** [comment]
It might be caused somewhere here: https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/blob/master/lua/anti_ddos_challenge.lua#L323

**Comment by C0nw0nk** [comment]
Looks like my stringrandom function needs rebuilding

**Comment by C0nw0nk** [comment]
Please let me know how it goes with the updated / latest version

**Comment by tamerciaga** [comment]
@C0nw0nk the issue is still there.

**Comment by C0nw0nk** [comment]
@tamerciaga @simon987 I have found the cause of the problem and updated the script tested myself please confirm the update has resolved the memory leak. https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/commit/eeee46a1351a8296053ed8d151b1f5add60ed563

The problem was in a for each loop i named the value for `key` as an underscore `_` what caused the problem.

**Comment by tamerciaga** [comment]
@C0nw0nk the memory leak seems to be fixed, nice!

I found another bug, not sure why it is happening, but the countdown doesn't work and the page doesn't get refreshed. I see the following JavaScript error in the Firefox console: `SyntaxError: expected expression, got '%'` on line 1. I think it has to do with the encryption/page loading.

**Comment by C0nw0nk** [comment]
Are you using the latest version the last update I did was to squash a bug
with Firefox
