### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by rx-209** [C0nw0nk/Nginx-Lua-Anti-DDoS#26]
Now using script for real ddos mitigation. When i instaled your script insted of my old code - cpu usage highly increased. 
![Screenshot_1](https://user-images.githubusercontent.com/32479898/76746983-73d8f400-6789-11ea-98be-e2b3398410f3.jpg)

**Comment by C0nw0nk** [comment]
You say old script before this update what update version are you comparing to. https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/commit/bf420a3e95144ed7022209295005b6b373051828

It will help me identify what is causing CPU hogging.

**Comment by rx-209** [comment]
Sorry for misunderstanding, old script - another code, not related to your repository.

**Comment by C0nw0nk** [comment]
@rx-209 I know your issue was unrelated to my code as you said but I went ahead and Optimized / squeezed my code for all the performance it can give you with Nginx and LuaJIT including having it cache regex.

https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/commit/3780ce93685789565e97e881f67c29a565a0fc16

If you want something i use in production on my own Nginx servers turn this feature on http://nginx.org/en/docs/ngx_core_module.html#pcre_jit

**Comment by rx-209** [comment]
Great, cpu load decreased by 1,5-2 times, thx.

**Comment by C0nw0nk** [comment]
@rx-209 No problem glad you see a huge performance impact i will tweak it further to get the last couple of things upto standard but you most likely won't see a performance gain because it will be such a small one it won't be noticeable.
