### ISSUE TITLE
Directadmin

### ISSUE THREAD

**Issue by ionel666** [C0nw0nk/Nginx-Lua-Anti-DDoS#30]
Hello,

Can this script run together with directadmin with nginx_apache mode?

**Comment by MaybeYesMaybeNot** [comment]
Script can work with everything, you just need lua module installed into nginx.

**Comment by C0nw0nk** [comment]
@ionel666 If your server has Nginx+Lua compiled or is a Openresty build https://openresty.org/en/download.html

Then yes it will but I don't know about directadmin and such because from what I looked up it is a control panel and I have never heard of "nginx_apache mode". So it is difficult for me to answer you other than to tell you If you are running Nginx and your Nginx build has Lua compiled with it or is a Openresty build then Yes this script will definetly work.
