### ISSUE TITLE
Bug with charset

### ISSUE THREAD

**Issue by gayanov** [C0nw0nk/Nginx-Lua-Anti-DDoS#8]
When I translate to my Russian language, i rain into a problem with charset, but i found a solution, seting attribute with value: charset="UTF-8" in 616 line
![image](https://user-images.githubusercontent.com/14072274/68892688-981db900-0734-11ea-8490-05fd6a4cef70.png)

**Comment by C0nw0nk** [comment]
I will update the script with your soloution. I assume it is because russian characters are a different charset and javascript needs it specified for those who translate this script into their own languages.

**Comment by C0nw0nk** [comment]
Also can you share your current script because i am curious how your translated script has that issue when i specified this in the HTML head.
https://github.com/C0nw0nk/Nginx-Lua-Anti-DDoS/blob/master/lua/anti_ddos_challenge.lua#L688-L689

That should already be fixing the issue without the need to add a charset tag to the javascript tag?

**Comment by gayanov** [comment]
Yes, of course, i set tag in javascript, another scripts

**Comment by gayanov** [comment]
I am change text innerHtml="Reload your page" in Russian language, without tag utf-8, after i set tag it successfull
![Zlw3drYsS6g](https://user-images.githubusercontent.com/14072274/68935845-4e6fb580-07aa-11ea-9110-82a939ec9a73.jpg)

**Comment by C0nw0nk** [comment]
@gayanov I will update the script with your soloution fantastic work and find :)

**Comment by C0nw0nk** [comment]
Fixed.
